In [1]:
!pip install PyTDC

In [2]:
!pip install scikit-learn

In [3]:
!pip install rdkit

In [4]:
from tdc.multi_pred import TrialOutcome
data = TrialOutcome(name = 'phase1') # 'phase2' / 'phase3'
split = data.get_split()

Found local copy...
Loading...
Done!


In [5]:
split["train"]

nctid         start_date      complete_date  \
0     NCT00002790         March 1996                NaN   
1     NCT00002863          June 1996          July 2000   
2     NCT00003005      December 1997         March 2001   
3     NCT00003060         March 1995  February 22, 2001   
4     NCT00003194          July 1997  December 19, 2002   
...           ...                ...                ...   
1677  NCT03605212  February 27, 2017      July 25, 2018   
1678  NCT03606707       June 1, 2018      July 15, 2018   
1679  NCT03652233   November 2, 2018      November 2021   
1680  NCT03672851     April 17, 2019      July 31, 2019   
1681  NCT04042051  November 12, 2019   November 2, 2020   

                                         drug_molecules  \
0     CC[C@@H]1NC(=O)[C@H]([C@H](O)[C@H](C)C\\C=C\\C...   
1     [H][C@@]12N(C)C3=CC(OC)=C(C=C3[C@@]11CCN3CC=C[...   
2     [H][C@@]1(CO)C[C@@]([H])(O)[C@@]([H])(O1)N1C=N...   
3     CS(=O)(=O)OCCCCOS(C)(=O)=O__ClCCN(CCCl)P1(=O)N...   
4     N[C@@H](CCCNC(N)=N)C(O)=O__ClCCN(CCCl)P1(=O)NC...   
...                                                 ...   
1677      CC(C)COC1=C(C=C(C=C1)C1=NC(C)=C(S1)C(O)=O)C#N   
1678  [H][C@@]12C[C@@H](C)[C@](O)(C(=O)CO)[C@@]1(C)C...   
1679  [H][N]1([H])[C@@H]2CCCC[C@H]2[N]([H])([H])[Pt]...   
1680  COC1=CC=CC=C1OC1=C(NS(=O)(=O)C2=CC=C(C=C2)C(C)...   
1681  COC1=C(OCCCN2CCOCC2)C=CC2=C1N=C(NC(=O)C1=CN=C(...   

                                               icdcodes  \
0     D89.810__D89.811__D89.813__D89.812__C95.91__C9...   
1     C96.A__C46.9__C96.22__C46.0__C46.2__C92.31__C9...   
2     C95.91__C95.92__Z80.6__Z85.6__C90.11__C90.12__...   
3     C43.51__C43.9__C43.52__D03.51__C43.8__Z85.820_...   
4     H01.009__H02.209__H02.009__H02.109__H04.209__H...   
...                                                 ...   
1677                                              E88.3   
1678  H53.9__O90.6__F01.50__F01.51__F03.90__F03.91__...   
1679  C22.0__C4A.9__C7B.1__C4A.0__C4A.31__C4A.51__C4...   
1680  C91.01__C91.02__C92.01__C92.02__C92.41__C92.42...   
1681  C79.81__D24.1__D24.2__D24.9__D49.3__C44.501__D...   

                                   eligibility_criteria  Y  
0     DISEASE CHARACTERISTICS: See General Eligibili...  0  
1     DISEASE CHARACTERISTICS: Biopsy-proven soft ti...  0  
2     DISEASE CHARACTERISTICS: TdT positive acute ly...  0  
3     DISEASE CHARACTERISTICS: Biopsy proven relapse...  0  
4     DISEASE CHARACTERISTICS: - Histologically prov...  0  
...                                                 ... ..  
1677  Inclusion Criteria: - male and female children...  0  
1678  Inclusion Criteria: - Patients with rheumatoid...  1  
1679   Inclusion Criteria: - Recurrent/metastatic Sq...  0  
1680  Inclusion Criteria: 1. Research patients enrol...  0  
1681  Inclusion Criteria: 1. Written informed consen...  0  

[1682 rows x 7 columns]

In [6]:
import time
from datetime import datetime

def get_timestamp(date_str):
    try:
        # Cas où le jour est présent (ex: "November 2, 2018")
        date_obj = datetime.strptime(date_str, "%B %d, %Y")
    except ValueError:
        # Cas où seul le mois et l'année sont présents (ex: "July 2000")
        date_obj = datetime.strptime(date_str, "%B %Y")
        date_obj = date_obj.replace(day=1)  # Ajouter le 1er du mois

    return int(date_obj.timestamp())  # Convertir en timestamp (secondes)

In [7]:
from rdkit import Chem
from rdkit.Chem import AllChem
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

# Encodeurs et scalers
drug_encoder = TfidfVectorizer()
icd_encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")
eligibility_encoder = TfidfVectorizer()
duration_scaler = StandardScaler()

def get_fingerprint(smiles, radius=2, n_bits=2048):
    """Génère l'empreinte moléculaire à partir du SMILES"""
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        return AllChem.GetMorganFingerprintAsBitVect(mol, radius, nBits=n_bits)
    else:
        return None

def compute_duration(start_date, complete_date):
    """ Calcule la durée en gérant les erreurs """
    duration = []
    for i in range(len(complete_date)):
        try:
            duration.append(get_timestamp(complete_date[i]) - get_timestamp(start_date[i]))
        except:
            duration.append(10**20)  # Valeur extrême pour éviter les erreurs
    return np.array(duration).reshape(-1, 1)  # S'assurer que c'est bien une colonne

def process_icdcodes(icd_codes):
    """ Transforme les icdcodes séparés par '__' en une liste de codes """
    return icd_codes.split("__") if isinstance(icd_codes, str) else []

def fit_transform_data(data):
    """ Applique fit_transform sur les données d'entraînement """
    global drug_encoder, icd_encoder, eligibility_encoder, duration_scaler  # On garde les mêmes encodeurs pour le test
    
    # Durée normalisée
    duration = compute_duration(data["start_date"], data["complete_date"])
    duration = duration_scaler.fit_transform(duration)  # Normalisation

    # Encodage des features
    drug_molecules = drug_encoder.fit_transform(np.array(data["drug_molecules"])).toarray()
    
    icdcodes = icd_encoder.fit_transform(np.array(data["icdcodes"]).reshape(-1, 1))
    
    eligibility_criteria = eligibility_encoder.fit_transform(np.array(data["eligibility_criteria"])).toarray()

    # Calcul des empreintes moléculaires
    fingerprints = []
    for smiles in data["drug_molecules"]:
        fp = get_fingerprint(smiles)
        if fp:
            fingerprints.append(fp)
        else:
            fingerprints.append(np.zeros(2048))  # Si l'empreinte est None, on remplit avec un vecteur de zéros

    fingerprints = np.array(fingerprints)

    # Concaténation des features
    X_train = np.concatenate([duration, drug_molecules, icdcodes, eligibility_criteria, fingerprints], axis=1)
    return X_train

def transform_data(data):
    """ Applique transform sur les données de test (sans réentraîner les encodeurs) """
    global drug_encoder, icd_encoder, eligibility_encoder, duration_scaler

    duration = compute_duration(data["start_date"], data["complete_date"])
    duration = duration_scaler.transform(duration)  # Normalisation

    drug_molecules = drug_encoder.transform(np.array(data["drug_molecules"])).toarray()
    
    icdcodes = icd_encoder.transform(np.array(data["icdcodes"]).reshape(-1, 1))
    
    eligibility_criteria = eligibility_encoder.transform(np.array(data["eligibility_criteria"])).toarray()

    # Calcul des empreintes moléculaires pour les données de test
    fingerprints = []
    for smiles in data["drug_molecules"]:
        fp = get_fingerprint(smiles)
        if fp:
            fingerprints.append(fp)
        else:
            fingerprints.append(np.zeros(2048))  # Si l'empreinte est None, on remplit avec un vecteur de zéros

    fingerprints = np.array(fingerprints)

    # Concaténation des features
    X_test = np.concatenate([duration, drug_molecules, icdcodes, eligibility_criteria, fingerprints], axis=1)
    return X_test

In [8]:
X_train = fit_transform_data(split["train"])  # Entraînement
Y_train_string = split["train"]["Y"]
Y_train = []

for k in range(len(Y_train_string)):
    Y_train.append(int(Y_train_string[k]))

Y_train = np.array(Y_train)

[18:37:18] SMILES Parse Error: syntax error while parsing: CC[C@@H]1NC(=O)[C@H]([C@H](O)[C@H](C)C\\C=C\\C)N(C)C(=O)[C@H](C(C)C)N(C)C(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H](C)NC(=O)[C@H](C)NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H](NC(=O)[C@H](CC(C)C)N(C)C(=O)CN(C)C1=O)C(C)C__CN(CC1=CN=C2N=C(N)N=C(N)C2=N1)C1=CC=C(C=C1)C(=O)N[C@@H](CCC(O)=O)C(O)=O__CC(=O)CC(C1=CC=CC=C1)C1=C(O)C2=C(OC1=O)C=CC=C2
[18:37:18] SMILES Parse Error: Failed parsing SMILES 'CC[C@@H]1NC(=O)[C@H]([C@H](O)[C@H](C)C\\C=C\\C)N(C)C(=O)[C@H](C(C)C)N(C)C(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H](C)NC(=O)[C@H](C)NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H](NC(=O)[C@H](CC(C)C)N(C)C(=O)CN(C)C1=O)C(C)C__CN(CC1=CN=C2N=C(N)N=C(N)C2=N1)C1=CC=C(C=C1)C(=O)N[C@@H](CCC(O)=O)C(O)=O__CC(=O)CC(C1=CC=CC=C1)C1=C(O)C2=C(OC1=O)C=CC=C2' for input: 'CC[C@@H]1NC(=O)[C@H]([C@H](O)[C@H](C)C\\C=C\\C)N(C)C(=O)[C@H](C(C)C)N(C)C(=O)[C@H](CC(C)C)N(C)C(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H](C)NC(=O)[C@H](C)NC(=O)[C@H](CC(C)C)N(C)C(=O)[C@@H](NC(=O)[

In [9]:
X_train

array([[ 9.6148034 ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.10400629,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.10400629,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.10400629,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.10400629,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.10400629,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [10]:
X_test = transform_data(split["test"])  # Transformation des données de test sans réentraîner

Y_test_string = split["test"]["Y"]
Y_test = []
for k in range(len(Y_test_string)):
    Y_test.append(int(Y_test_string[k]))

Y_test = np.array(Y_test)

[18:37:25] SMILES Parse Error: syntax error while parsing: [H][C@@]1(C[C@@H](C)[C@]2([H])CC(=O)[C@H](C)\\C=C(C)\\[C@@H](O)[C@@H](OC)C(=O)[C@H](C)C[C@H](C)\\C=C\\C=C\\C=C(C)\\[C@H](C[C@]3([H])CC[C@@H](C)[C@@](O)(O3)C(=O)C(=O)N3CCCC[C@@]3([H])C(=O)O2)OC)CC[C@@H](O)[C@@H](C1)OC__NC1=CC=CC2=C1CN(C1CCC(=O)NC1=O)C2=O
[18:37:25] SMILES Parse Error: Failed parsing SMILES '[H][C@@]1(C[C@@H](C)[C@]2([H])CC(=O)[C@H](C)\\C=C(C)\\[C@@H](O)[C@@H](OC)C(=O)[C@H](C)C[C@H](C)\\C=C\\C=C\\C=C(C)\\[C@H](C[C@]3([H])CC[C@@H](C)[C@@](O)(O3)C(=O)C(=O)N3CCCC[C@@]3([H])C(=O)O2)OC)CC[C@@H](O)[C@@H](C1)OC__NC1=CC=CC2=C1CN(C1CCC(=O)NC1=O)C2=O' for input: '[H][C@@]1(C[C@@H](C)[C@]2([H])CC(=O)[C@H](C)\\C=C(C)\\[C@@H](O)[C@@H](OC)C(=O)[C@H](C)C[C@H](C)\\C=C\\C=C\\C=C(C)\\[C@H](C[C@]3([H])CC[C@@H](C)[C@@](O)(O3)C(=O)C(=O)N3CCCC[C@@]3([H])C(=O)O2)OC)CC[C@@H](O)[C@@H](C1)OC__NC1=CC=CC2=C1CN(C1CCC(=O)NC1=O)C2=O'
[18:37:25] SMILES Parse Error: syntax error while parsing: CN(C1=CC2=NN(C)C(C)=C2C=C1)C1=CC=NC(NC2=CC=C(C)C(=C2

In [11]:
# Model random lineaire
from sklearn.linear_model import LogisticRegression  # Or LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix

# Initialize the model (for logistic regression if Y is binary)
model = LogisticRegression()

model.fit(X_train, Y_train)

# Make predictions
Y_pred = model.predict(X_test)  # Assuming X_test and Y_test are available for evaluation

# Evaluate the model
print("Accuracy:", accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

Accuracy: 0.6166666666666667
Confusion Matrix:
 [[ 92 114]
 [ 70 204]]


In [12]:
from sklearn.metrics import accuracy_score, confusion_matrix
import xgboost as xgb

# Initialize the XGBoost model for binary classification
model = xgb.XGBClassifier(
    objective='binary:logistic',  # For binary classification
    colsample_bytree=0.3,         # Fraction of features to use
    learning_rate=0.1,            # Learning rate
    max_depth=5,                  # Maximum depth of trees
    alpha=10,                     # L2 regularization
    n_estimators=200              # Number of trees
)

# Fit the model to the training data
model.fit(X_train, Y_train)

# Make predictions on the test data
Y_pred = model.predict(X_test)

# Evaluate the model
print("Accuracy:", accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))

Accuracy: 0.5916666666666667
Confusion Matrix:
 [[ 79 127]
 [ 69 205]]
